name: 'Markdown Documentation Formatter'
description: 'Formats product documentation written in markdown.'
inputs:
  input:
    description: 'The location of the documentation within the repository (default: ./docs).'
    required: true
    default: './docs'
  output:
    description: 'Where to put the processed results (default: ./processed).'
    required: true
    default: './processed'
  style:
    description: 'The style of processing to do (github | confluence | custom).'
    required: true
    default: 'confluence'
  args:
    description: 'The extended command line args, see the readme.'
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.2
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.11
    - name: install mddocformatter
      shell: bash
      run: pip install .
    - name: run mddocformatter
      shell: bash
      run: |
      mddocformatter --input ${{ inputs.input }} --output ${{ inputs.output }} --style ${{ inputs.style }} ${{ args }}
