[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mddocproc"
authors = [
    {name = "Jonathan Pierce", email = "markdown.documentation.processing"},
]
description = "My package description"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["markdown", "confluence"]
license = {text = "Apache License (2.0)", file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = []
dynamic = ["version"]

[project.scripts]
main = "mddocproc:_main"

[tool.black]
line-length = 120
