name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-python@v5.0.0
      - uses: py-actions/flake8@v2.3.0
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-python@v5.0.0
      - run: |
          python -m venv venv
          source ./venv/bin/activate
      - run: python -m pip install -r requirements.txt || true
      - run: python -m pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pytest:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install pytest-cov
        run: pip install pytest pytest-cov
      - name: install dependencies
        run: pip install -e .[test]
      - name: run pytest --cov
        run: |
          set -e
          pytest --cov=./ --cov-report=xml
          : .coverage confuses coveralls, remove it
          rm -f .coverage
      - name: upload coverage data to coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  coveralls-finish:
    if: inputs.coveralls
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2.2.3
        with:
          parallel-finished: true
