name: Test End to End
on:
  workflow_run:
    workflows: ['Update Beta Tag']
    types:
      - completed
jobs:
  test_confluence_formatting:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Package the test documentation using the confluence style and upload it as an artifact.
    steps:
      - uses: actions/checkout@v4
      - uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: './tests/data/docs'
          output: './tests/data/processed_confluence'
          style: 'confluence'
          args: '--version test'
      - uses: actions/upload-artifact@v4
        with:
          name: 'processed_confluence'
          path: './tests/data/processed_confluence'
      - uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: './tests/data/docs'
          validate: true
          style: 'confluence'
          args: '--version test'
  test_github_formatting:
    runs-on: ubuntu-latest
    name: Package the test documentation using the github style and upload it as an artifact.
    steps:
      - uses: actions/checkout@v4
      - uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: './tests/data/docs'
          output: './tests/data/processed_github'
          style: 'github'
          args: '--version test'
      - uses: actions/upload-artifact@v4
        with:
          name: 'processed_github'
          path: './tests/data/processed_github'
      - uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: './tests/data/docs'
          style: 'github'
          validate: true
          args: '--version test'
