name: Test End to End
on:
  workflow_run:
    workflows: ['Update Beta Tag']
    types:
      - completed
jobs:
  format_test_docs_confluence_style:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Format Docs - Confluence Style.
    outputs:
      processed: ${{ steps.process-confluence.outputs.processed }}
    steps:
      - uses: actions/checkout@v4
      - name: Process test/docs in confluence style
        id: process-confluence
        uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: './tests/data/docs'
          output: './tests/data/processed_confluence'
          style: 'confluence'
          args: '--version test'
  validate_test_docs_confluence_style:
    runs-on: ubuntu-latest
    needs: format_test_docs_confluence_style
    name: Validate Docs - Confluence Style
    steps:
      - name: Validate result
        uses: originaldaemon/markdown-documentation-formatter@beta
        with:
          input: ${{ needs.format_test_docs_confluence_style.outputs.processed }}
          validate: true
          style: 'confluence'
          args: '--version test'
  upload_artifact_confluence_style:
    runs-on: ubuntu-latest
    needs: format_test_docs_confluence_style
    name: Update Results - Confluence Style
    steps:
      - name: Upload processed as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'processed_confluence'
          path: ${{ needs.format_test_docs_confluence_style.outputs.processed }}
